spring:
  application:
    name: STAFF-SERVICE
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

openapi:
  service:
    title: STAFF-SERVICE DOC
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /STAFF-SERVICE/v3/api-docs
  swagger-ui:
    path: /STAFF-SERVICE/swagger-ui.html

#  security:
#    user:
#      name: jay
#      password: 1234

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

vonage:
  api-key:
  api-secret:
