spring:
  application:
    name: BUS-SERVICE

  data:
    mongodb:
      uri:
#      database: booking

openapi:
  service:
    title: BUS-SERVICE DOC
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /BUS-SERVICE/v3/api-docs
  swagger-ui:
    path: /BUS-SERVICE/swagger-ui.html

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost