spring:
  application:
    name: USER-SERVICE
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


#  security:
#    user:
#      name: jay
#      password: 1234

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

vonage:
  api-key:
  api-secret:

redis:
  host:
  port:
  password: